### ISSUE TITLE
Calculating rpkm fails 

### ISSUE THREAD

**Issue by Puneet-Shivanand** [nkrumm/CoNIFER#9]
@nkrumm 
conifer throws out this error please do mention what i did wrong 
have attached the probes.txt  file and the indexed bam file that i am using
[probes.txt](https://github.com/nkrumm/CoNIFER/files/279828/probes.txt)

```
   [INIT] Successfully read in 194080 probes from ../sampledata/probes.txt
   [RUNNING] Counting total number of reads in bam file...
   [RUNNING] Found 2083467 reads
   [RUNNING] Calculating RPKM values...
   conifer.py:617: RuntimeWarning: invalid value encountered in divide
      rpkm = (10**9*(readcount)/(exon_bp))/(total_reads)
```

when i tried conifer on another machine this error pops up 

`Traceback (most recent call last):
  File "conifer.py", line 682, in <module>
    args.func(args)
  File "conifer.py", line 564, in CF_bam2RPKM
    if not f._hasIndex():
AttributeError: 'pysam.csamfile.Samfile' object has no attribute '_hasIndex'`

your help is much appreciated

**Comment by thw17** [comment]
Hi Puneet,

I ran into your second error as well and think that it might stem from incompatibility between CoNIFER and more recent versions of PySam.  I downgraded PySam to version 0.8.3 and this solved my problem.  Because I was also running into an error related to CoNIFER's incompatibility with recent versions of Numpy (conifer.py:157: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 101 but corresponding boolean dimension is 100), I found it easiest to just create an Anaconda environment specifically for CoNIFER containing PySam 0.8.3 and Numpy 1.9.3.  All steps of the CoNIFER pipeline seem to work in this environment.

Best,
Tim

**Comment by Puneet-Shivanand** [comment]
Thanks @thw17 ,

Will try conifer with the specified version of pysam and numpy

**Comment by andreyleonardo** [comment]
Hey.

I'm having the same issue reported by Punnet
```
conifer.py:617: RuntimeWarning: invalid value encountered in divide
      rpkm = (10**9*(readcount)/(exon_bp))/(total_reads)
```

I'm using Python 2.7, Pysam 0.8.3, Numpy 1.9.3 and Pytables 2.3.1.
I tried with different bam files and all of them stops the process with this same error.

Someone knows how to fix this issue?

**Comment by JuanmaMedina** [comment]
> Hey.
> 
> I'm having the same issue reported by Punnet
> 
> ```
> conifer.py:617: RuntimeWarning: invalid value encountered in divide
>       rpkm = (10**9*(readcount)/(exon_bp))/(total_reads)
> ```
> 
> I'm using Python 2.7, Pysam 0.8.3, Numpy 1.9.3 and Pytables 2.3.1.
> I tried with different bam files and all of them stops the process with this same error.
> 
> Someone knows how to fix this issue?

I arrived really late to the party, but just in case: 
https://sourceforge.net/p/conifer/discussion/general/thread/9bc0fa8a/

I.e., this warning means that there are 0-length exons in the probes file, which will be removed later on (in the `analyze` step all probes that have a median RPKM < 1 across all samples are removed)
